{
 "title": "Viessmann Wärmepumpe – All-in-One Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "korrekturfaktor", "label": "Korrekturfaktor Strom", "query": "1.0" },
   { "name": "start_wirtschaftsjahr", "label": "Start Wirtschaftsjahr", "query": "16.12.2025" },
   {
    "name": "anlage_id",
    "label": "Anlage",
    "query": "select installation_id from temperature_snapshots  group by installation_id"
   },
   { "name": "granularity", "label": "Monat/Jahr", "query": "'Monat', 'Jahr'" }
  ]
 },
 "panels": [
  {
   "title": "Außentemperatur",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "\r\n\r\nSELECT outside_temp as 'Aktuell' from temperature_snapshots_stat  where installation_id = 1234567 order by timestamp_mez desc Limit 1\r\n",
     "rawQueryText": "\r\n\r\nSELECT outside_temp as 'Aktuell' from temperature_snapshots_stat  where installation_id = ${anlage_id} order by timestamp_mez desc Limit 1\r\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Warmwasser",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT dhw_temp as 'Warmwassertemperatur_aktuell' from temperature_snapshots_stat  where installation_id = 1234567 order by timestamp_mez desc Limit 1\n\n",
     "rawQueryText": "SELECT dhw_temp as 'Warmwassertemperatur_aktuell' from temperature_snapshots_stat  where installation_id = ${anlage_id} order by timestamp_mez desc Limit 1\n\n",
     "rawSql": "SELECT dhw_temp AS value FROM temperature_snapshots_grafana where installation_id = '7654321' ORDER BY timestamp DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Pufferspeicher",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT buffer_temp as 'Aktuell' from temperature_snapshots_stat where installation_id = ${anlage_id} order by timestamp_mez desc Limit 1",
     "rawQueryText": "SELECT buffer_temp as 'Aktuell' from temperature_snapshots_stat where installation_id = ${anlage_id} order by timestamp_mez desc Limit 1",
     "rawSql": "SELECT compressor_power AS value FROM temperature_snapshots_grafana where installation_id = '7654321' ORDER BY timestamp DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Wärmeleistung aktuell",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT thermal_power\nfrom temperature_snapshots_stat  \nwhere installation_id = ${anlage_id} order by timestamp_mez desc \nLimit 1",
     "rawQueryText": "SELECT thermal_power\nfrom temperature_snapshots_stat  \nwhere installation_id = ${anlage_id} order by timestamp_mez desc \nLimit 1",
     "rawSql": "SELECT compressor_power AS value FROM temperature_snapshots_grafana where installation_id = '7654321' ORDER BY timestamp DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Kompressor aktuell",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "Select  compressor_speed from temperature_snapshots_stat  where installation_id = 1234567 order by timestamp_mez desc limit 1",
     "rawQueryText": "Select  compressor_speed from temperature_snapshots_stat  where installation_id = ${anlage_id} order by timestamp_mez desc limit 1",
     "rawSql": "SELECT compressor_active AS value FROM temperature_snapshots_grafana where installation_id = '7654321' ORDER BY timestamp DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Spreizung aktuell",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "Select timestamp_mez,hp_secondary_circuit_supply_temp - return_temp as 'Spreizung_calc' from temperature_snapshots_stat  where installation_id = 1234567 order by  timestamp_mez desc limit 1",
     "rawQueryText": "Select timestamp_mez,hp_secondary_circuit_supply_temp - return_temp as 'Spreizung_calc' from temperature_snapshots_stat  where installation_id = ${anlage_id} order by  timestamp_mez desc limit 1",
     "rawSql": "SELECT CASE WHEN compressor_power>0 THEN thermal_power/compressor_power END AS value FROM temperature_snapshots_grafana where installation_id = '7654321' ORDER BY timestamp DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Volumenstrom",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "\nSelect\nvolumetric_flow,\n'l/min' as Unit\nfrom temperature_snapshots_stat  \nwhere installation_id = 1234567 \norder by timestamp_mez desc \nlimit 1",
     "rawQueryText": "\nSelect\nvolumetric_flow,\n'l/min' as Unit\nfrom temperature_snapshots_stat  \nwhere installation_id = ${anlage_id} \norder by timestamp_mez desc \nlimit 1",
     "rawSql": "SELECT volumetric_flow AS value FROM temperature_snapshots_grafana where installation_id = '7654321' ORDER BY timestamp DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Leistungsaufnahme aktuell",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT elektrische_Leistung * 1.0 * 60 / sample_interval\r\n as 'Aktuell' from temperature_snapshots_stat  where installation_id = 1234567 order by timestamp_mez desc Limit 1",
     "rawQueryText": "SELECT elektrische_Leistung * ${korrekturfaktor} * 60 / sample_interval\r\n as 'Aktuell' from temperature_snapshots_stat  where installation_id = ${anlage_id} order by timestamp_mez desc Limit 1",
     "rawSql": "SELECT compressor_power AS value FROM temperature_snapshots_grafana where installation_id = '7654321' ORDER BY timestamp DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "COP  aktuell",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \nthermal_power /\n((elektrische_Leistung *${korrekturfaktor} * 60 / sample_interval)/1000) \nas 'cop_aktuell'\nFrom temperature_snapshots_stat\nwhere installation_id = ${anlage_id}\norder by timestamp_mez desc\nLimit 1\n",
     "rawQueryText": "SELECT \nthermal_power /\n((elektrische_Leistung *${korrekturfaktor} * 60 / sample_interval)/1000) \nas 'cop_aktuell'\nFrom temperature_snapshots_stat\nwhere installation_id = ${anlage_id}\norder by timestamp_mez desc\nLimit 1\n",
     "rawSql": "SELECT (MAX(thermal_energy)-MIN(thermal_energy))/(MAX(electrical_energy)-MIN(electrical_energy)) AS value FROM temperature_snapshots_grafana WHERE installation_id = '7654321', date(timestamp)=date('now')",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Anlagendruck",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "Select timestamp_mez,\npressure_supply from temperature_snapshots_stat\nwhere installation_id = 1234567 order by timestamp_mez desc \nlimit 1",
     "rawQueryText": "Select timestamp_mez,\npressure_supply from temperature_snapshots_stat\nwhere installation_id = ${anlage_id} order by timestamp_mez desc \nlimit 1",
     "rawSql": "SELECT volumetric_flow AS value FROM temperature_snapshots_grafana where installation_id = '7654321' ORDER BY timestamp DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select \nmin(outside_temp) as 'Min' from temperature_snapshots_stat where strftime('%F',timestamp_mez) = date('now', 'localtime') and  installation_id = 1234567\n\n\n",
     "rawQueryText": "select \nmin(outside_temp) as 'Min' from temperature_snapshots_stat where strftime('%F',timestamp_mez) = date('now', 'localtime') and  installation_id = ${anlage_id}\n\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select \nmax(outside_temp) as 'Max' from temperature_snapshots_stat where strftime('%F',timestamp_mez) = date('now', 'localtime') and installation_id = ${anlage_id}\n\n",
     "rawQueryText": "select \nmax(outside_temp) as 'Max' from temperature_snapshots_stat where strftime('%F',timestamp_mez) = date('now', 'localtime') and installation_id = ${anlage_id}\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select \nmin(dhw_temp) as 'Min' from temperature_snapshots_stat where strftime('%F',timestamp_mez) = date('now', 'localtime') and installation_id = ${anlage_id} \n\n\n",
     "rawQueryText": "select \nmin(dhw_temp) as 'Min' from temperature_snapshots_stat where strftime('%F',timestamp_mez) = date('now', 'localtime') and installation_id = ${anlage_id} \n\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select \nmax(dhw_temp) as 'Max' from temperature_snapshots_stat where strftime('%F',timestamp_mez) = date('now', 'localtime') and installation_id = 1234567 \n\n",
     "rawQueryText": "select \nmax(dhw_temp) as 'Max' from temperature_snapshots_stat where strftime('%F',timestamp_mez) = date('now', 'localtime') and installation_id = ${anlage_id} \n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select \nmin(buffer_temp) as 'Min' from temperature_snapshots_stat where strftime('%F',timestamp_mez) = date('now', 'localtime') and installation_id = ${anlage_id} \n\n\n",
     "rawQueryText": "select \nmin(buffer_temp) as 'Min' from temperature_snapshots_stat where strftime('%F',timestamp_mez) = date('now', 'localtime') and installation_id = ${anlage_id} \n\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select \nmax(buffer_temp) as 'Max' from temperature_snapshots_stat where strftime('%F',timestamp_mez) = date('now', 'localtime') and installation_id = ${anlage_id} \n\n",
     "rawQueryText": "select \nmax(buffer_temp) as 'Max' from temperature_snapshots_stat where strftime('%F',timestamp_mez) = date('now', 'localtime') and installation_id = ${anlage_id} \n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Vorlauf / Rücklauf / Heizkreis-Vorlauf / Pufferspeicher / Warmwasser",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "queryText": "SELECT\r\n  CAST(strftime('%s', timestamp, 'utc') AS INTEGER) AS time,\r\n  coalesce(cast(replace(hp_secondary_circuit_supply_temp,',', '.') as REAL), 0) * 1.0 AS Vorlauf,\r\n  return_temp AS Rücklauf,\r\n  coalesce(buffer_temp, 0) as Pufferspeicher,\r\n  coalesce(dhw_temp, 0) as Warmwasser,\r\n  coalesce(cast(replace(heating_circuit_1_supply_temp, ',', '.') as REAL), 0) * 1.0 as 'Heizkreis-Vorlauf'\r\nFROM temperature_snapshots_stat\r\nwhere  installation_id = 1234567 \r\nORDER BY time asc\r\n\r\n",
     "rawQueryText": "SELECT\r\n  CAST(strftime('%s', timestamp, 'utc') AS INTEGER) AS time,\r\n  coalesce(cast(replace(hp_secondary_circuit_supply_temp,',', '.') as REAL), 0) * 1.0 AS Vorlauf,\r\n  return_temp AS Rücklauf,\r\n  coalesce(buffer_temp, 0) as Pufferspeicher,\r\n  coalesce(dhw_temp, 0) as Warmwasser,\r\n  coalesce(cast(replace(heating_circuit_1_supply_temp, ',', '.') as REAL), 0) * 1.0 as 'Heizkreis-Vorlauf'\r\nFROM temperature_snapshots_stat\r\nwhere  installation_id = ${anlage_id} \r\nORDER BY time asc\r\n\r\n",
     "rawSql": "SELECT strftime('%s',timestamp)*1000 AS time, supply_temp AS Vorlauf, return_temp AS Ruecklauf, outside_temp AS Aussen FROM temperature_snapshots_grafana WHERE installation_id = '7654321', $__timeFilter(strftime('%s',timestamp)*1000)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Stromverbrauch & Wärmeleistung",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "queryText": "SELECT\r\n  CAST(strftime('%s', timestamp, 'utc') as integer) AS time,\r\n  coalesce(elektrische_Leistung,0) * 1.05 *60 / sample_interval AS Stromverbrauch,\r\n  coalesce (wärmeleistung, 0) *60 / sample_interval as Leistung\r\n  \r\nFROM temperature_snapshots_stat\r\nwhere  installation_id = 1234567 \r\nORDER BY time asc\r\n\r\n",
     "rawQueryText": "SELECT\r\n  CAST(strftime('%s', timestamp, 'utc') as integer) AS time,\r\n  coalesce(elektrische_Leistung,0) * ${korrekturfaktor} *60 / sample_interval AS Stromverbrauch,\r\n  coalesce (wärmeleistung, 0) *60 / sample_interval as Leistung\r\n  \r\nFROM temperature_snapshots_stat\r\nwhere  installation_id = ${anlage_id} \r\nORDER BY time asc\r\n\r\n",
     "rawSql": "SELECT strftime('%s',timestamp)*1000 AS time, compressor_power AS Strom, thermal_power AS Waerme FROM temperature_snapshots_grafana WHERE installation_id = '7654321', $__timeFilter(strftime('%s',timestamp)*1000)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "queryText": "SELECT\r\n        strftime('%s', event_timestamp_start) AS time,\r\n        strftime('%s', event_timestamp_end) AS timeEnd,\r\n    CAST(betriebszustand AS TEXT) AS state\r\nFROM event_betriebszustand_timeline\r\nWHERE installation_id = ${anlage_id}\r\nORDER BY event_timestamp_end ASC;\r\n\r\n",
     "rawQueryText": "SELECT\r\n        strftime('%s', event_timestamp_start) AS time,\r\n        strftime('%s', event_timestamp_end) AS timeEnd,\r\n    CAST(betriebszustand AS TEXT) AS state\r\nFROM event_betriebszustand_timeline\r\nWHERE installation_id = ${anlage_id}\r\nORDER BY event_timestamp_end ASC;\r\n\r\n",
     "rawSql": "SELECT strftime('%s',timestamp)*1000 AS time, compressor_power AS Strom, thermal_power AS Waerme FROM temperature_snapshots_grafana WHERE installation_id = '7654321', $__timeFilter(strftime('%s',timestamp)*1000)",
     "timeColumns": [
      "time",
      "timeEnd"
     ]
    }
   ]
  },
  {
   "title": "Kompressor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n   CASE\n       WHEN compressor_active = 1 THEN 1\n       WHEN compressor_active = 0 THEN 0\n       ELSE 2\n   END \nFROM temperature_snapshots_stat\nwhere  installation_id = 7654321 \nORDER BY timestamp_mez DESC\nLIMIT 1\n\n",
     "rawQueryText": "SELECT\n   CASE\n       WHEN compressor_active = 1 THEN 1\n       WHEN compressor_active = 0 THEN 0\n       ELSE 2\n   END \nFROM temperature_snapshots_stat\nwhere  installation_id = ${anlage_id} \nORDER BY timestamp_mez DESC\nLIMIT 1\n\n",
     "rawSql": "SELECT strftime('%s',timestamp)*1000 AS time, CASE WHEN compressor_power>0 THEN thermal_power/compressor_power END AS COP FROM temperature_snapshots_grafana WHERE installation_id = '7654321', $__timeFilter(strftime('%s',timestamp)*1000)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Betriebsmodus",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "WITH last_snapshot AS (\n    SELECT *\n    FROM temperature_snapshots_stat\n    WHERE installation_id = 1234567\n    ORDER BY timestamp_mez DESC\n    LIMIT 1\n)\n\nSELECT\n    datetime(substr(e.event_timestamp,1,19),'localtime') AS event_timestamp_mez,\n    e.error_code,\n\n    CASE\n        WHEN ls.volumetric_flow > 0 AND ls.compressor_active = 0                         THEN 4  -- Standby\n        WHEN ls.volumetric_flow = 0 AND ls.compressor_active = 0                         THEN 5  -- Aus\n\n        WHEN e.error_code IN ('S.127','S.128','S.135','S.176')\n             OR (ls.volumetric_flow >= 1630 AND ls.compressor_active = 1)                THEN 1  -- Abtauen\n\n        WHEN e.error_code IN ('S.118','S.124','S.125','S.129')\n             OR (ls.volumetric_flow BETWEEN 1400 AND 1630 AND ls.compressor_active = 1)  THEN 2  -- Heizen\n\n        WHEN e.error_code = 'S.115'\n             OR (ls.volumetric_flow < 1100 AND ls.compressor_active = 1)                 THEN 3  -- Warmwasser\n\n        ELSE 6                                                                                   -- n/a\n    END AS betriebsstatus_code,\n\n    ls.timestamp_mez AS snapshot_timestamp\n\nFROM events e\nCROSS JOIN last_snapshot ls\nWHERE e.error_code <> 'S.187'\n  AND e.active = 1\n  AND e.installation_id = 1234567\nORDER BY event_timestamp_mez DESC, e.error_code ASC\nLIMIT 1\n\n",
     "rawQueryText": "WITH last_snapshot AS (\n    SELECT *\n    FROM temperature_snapshots_stat\n    WHERE installation_id = ${anlage_id}\n    ORDER BY timestamp_mez DESC\n    LIMIT 1\n)\n\nSELECT\n    datetime(substr(e.event_timestamp,1,19),'localtime') AS event_timestamp_mez,\n    e.error_code,\n\n    CASE\n        WHEN ls.volumetric_flow > 0 AND ls.compressor_active = 0                         THEN 4  -- Standby\n        WHEN ls.volumetric_flow = 0 AND ls.compressor_active = 0                         THEN 5  -- Aus\n\n        WHEN e.error_code IN ('S.127','S.128','S.135','S.176')\n             OR (ls.volumetric_flow >= 1630 AND ls.compressor_active = 1)                THEN 1  -- Abtauen\n\n        WHEN e.error_code IN ('S.118','S.124','S.125','S.129')\n             OR (ls.volumetric_flow BETWEEN 1400 AND 1630 AND ls.compressor_active = 1)  THEN 2  -- Heizen\n\n        WHEN e.error_code = 'S.115'\n             OR (ls.volumetric_flow < 1100 AND ls.compressor_active = 1)                 THEN 3  -- Warmwasser\n\n        ELSE 6                                                                                   -- n/a\n    END AS betriebsstatus_code,\n\n    ls.timestamp_mez AS snapshot_timestamp\n\nFROM events e\nCROSS JOIN last_snapshot ls\nWHERE e.error_code <> 'S.187'\n  AND e.active = 1\n  AND e.installation_id = ${anlage_id}\nORDER BY event_timestamp_mez DESC, e.error_code ASC\nLIMIT 1\n\n",
     "rawSql": "SELECT strftime('%s',timestamp)*1000 AS time, CASE WHEN compressor_power>0 THEN thermal_power/compressor_power END AS COP FROM temperature_snapshots_grafana WHERE installation_id = '7654321', $__timeFilter(strftime('%s',timestamp)*1000)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "externe Heizung",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "\nSelect  \ncase \n     when secondary_heat_generator_status = 'standby' then 1\n     when secondary_heat_generator_status = 'heating' then 2\n     when secondary_heat_generator_status is NULL then 4\n     else 3\n     END \n     as Zusatzheizung\n     \nfrom temperature_snapshots_stat where installation_id = 1234567  order by timestamp_mez desc limit 1",
     "rawQueryText": "\nSelect  \ncase \n     when secondary_heat_generator_status = 'standby' then 1\n     when secondary_heat_generator_status = 'heating' then 2\n     when secondary_heat_generator_status is NULL then 4\n     else 3\n     END \n     as Zusatzheizung\n     \nfrom temperature_snapshots_stat where installation_id = ${anlage_id}  order by timestamp_mez desc limit 1",
     "rawSql": "SELECT volumetric_flow AS value FROM temperature_snapshots_grafana where installation_id = '7654321' ORDER BY timestamp DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Laufzeit heute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT timestamp_mez, SUM(compressor_active * sample_interval) * 60 as Sekunden, \n    installation_id,\n    strftime('%Y-%m-%d', timestamp_mez) AS day,\n    substr(time(SUM(compressor_active * sample_interval) * 60, 'unixepoch' ), 1, 5) AS runtime_hhmm\nFROM temperature_snapshots_stat\nWHERE installation_id = 1234567  -- Grafana ersetzt automatisch\nGROUP BY day\nORDER BY day desc\nLIMIT 1\n",
     "rawQueryText": "SELECT timestamp_mez, SUM(compressor_active * sample_interval) * 60 as Sekunden, \n    installation_id,\n    strftime('%Y-%m-%d', timestamp_mez) AS day,\n    substr(time(SUM(compressor_active * sample_interval) * 60, 'unixepoch' ), 1, 5) AS runtime_hhmm\nFROM temperature_snapshots_stat\nWHERE installation_id = ${anlage_id}  -- Grafana ersetzt automatisch\nGROUP BY day\nORDER BY day desc\nLIMIT 1\n",
     "rawSql": "SELECT volumetric_flow AS value FROM temperature_snapshots_grafana where installation_id = '7654321' ORDER BY timestamp DESC LIMIT 1",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "letztes Update",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "Select strftime('%d.%m.%g', timestamp_mez) as 'Tag', strftime('%R', timestamp_mez) as 'Uhrzeit'\nfrom temperature_snapshots_stat\nwhere installation_id = 1234567 \norder by timestamp_mez desc\nLimit 1",
     "rawQueryText": "Select strftime('%d.%m.%g', timestamp_mez) as 'Tag', strftime('%R', timestamp_mez) as 'Uhrzeit'\nfrom temperature_snapshots_stat\nwhere installation_id = ${anlage_id} \norder by timestamp_mez desc\nLimit 1",
     "rawSql": "SELECT MAX(compressor_hours)-MIN(compressor_hours) AS value FROM temperature_snapshots_grafana WHERE installation_id = '7654321', date(timestamp)=date('now')",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Energieverteilung der letzten 14 Tage",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 10, "y": 22 },
   "targets": [
    {
     "queryText": "SELECT\r\n strftime('%d.%m', timestamp_mez) as 'Datum',\r\n \r\n  SUM(elektrische_Leistung * 1.0) / 1000 AS Strom,\r\n  SUM(Wärmeleistung) / 1000 AS Waerme\r\nFROM temperature_snapshots_stat\r\nwhere  strftime('%F', timestamp_mez) <= strftime('%F', datetime(1769650476767 / 1000, 'unixepoch', 'localtime'))\r\nand installation_id = 1234567 \r\nGROUP BY strftime('%F', timestamp_mez)\r\nORDER BY strftime('%F', timestamp_mez) desc\r\nLimit 14",
     "rawQueryText": "SELECT\r\n strftime('%d.%m', timestamp_mez) as 'Datum',\r\n \r\n  SUM(elektrische_Leistung * ${korrekturfaktor}) / 1000 AS Strom,\r\n  SUM(Wärmeleistung) / 1000 AS Waerme\r\nFROM temperature_snapshots_stat\r\nwhere  strftime('%F', timestamp_mez) <= strftime('%F', datetime($__to / 1000, 'unixepoch', 'localtime'))\r\nand installation_id = ${anlage_id} \r\nGROUP BY strftime('%F', timestamp_mez)\r\nORDER BY strftime('%F', timestamp_mez) desc\r\nLimit 14",
     "rawSql": "SELECT SUM(CASE WHEN compressor_active=1 AND LAG(compressor_active) OVER (ORDER BY timestamp)=0 THEN 1 ELSE 0 END) AS value FROM temperature_snapshots_grafana WHERE installation_id = '7654321', date(timestamp)=date('now')",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Energieverteilung heute",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\r\n    sum(Wärmeleistung / 1000) as 'Tageswärmeleistung',\r\n   sum(elektrische_Leistung / 1000 * 1.05) as 'Tagesstromverbrauch'\r\n\r\n  \r\nFrom temperature_snapshots_stat\r\nwhere  installation_id = 1234567 \r\ngroup by strftime('%F', timestamp_mez)\r\norder by installation_id desc, strftime('%F', timestamp_mez) desc\r\nLimit 1\r\n",
     "rawQueryText": "SELECT\r\n    sum(Wärmeleistung / 1000) as 'Tageswärmeleistung',\r\n   sum(elektrische_Leistung / 1000 * ${korrekturfaktor}) as 'Tagesstromverbrauch'\r\n\r\n  \r\nFrom temperature_snapshots_stat\r\nwhere  installation_id = ${anlage_id} \r\ngroup by strftime('%F', timestamp_mez)\r\norder by installation_id desc, strftime('%F', timestamp_mez) desc\r\nLimit 1\r\n",
     "rawSql": "SELECT (MAX(thermal_energy)-MIN(thermal_energy))/(MAX(electrical_energy)-MIN(electrical_energy)) AS value FROM temperature_snapshots_grafana WHERE installation_id = '7654321', strftime('%Y-%m',timestamp)=strftime('Y-%m','now')",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "Select \nSum( Case\n   when compressor_ein_aus > 0 then 1\n    else 0\n    end) as 'Kompressorstarts'\n\n\nFROM \"temperature_snapshots_takte_heute\"\nwhere installation_id = 1234567\ngroup by strftime('%F', timestamp_mez)\norder by timestamp_mez desc\nLimit 1",
     "rawQueryText": "Select \nSum( Case\n   when compressor_ein_aus > 0 then 1\n    else 0\n    end) as 'Kompressorstarts'\n\n\nFROM \"temperature_snapshots_takte_heute\"\nwhere installation_id = ${anlage_id}\ngroup by strftime('%F', timestamp_mez)\norder by timestamp_mez desc\nLimit 1",
     "rawSql": "SELECT (MAX(thermal_energy)-MIN(thermal_energy))/(MAX(electrical_energy)-MIN(electrical_energy)) AS value FROM temperature_snapshots_grafana WHERE installation_id = '7654321', date(timestamp)=date('now')",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Tagesarbeitszahl der letzten 14 Tage",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "queryText": "SELECT\n      strftime('%d.%m', timestamp_mez) as 'Datum',\n      CASE strftime('%w', timestamp_mez)\n        WHEN '0' THEN 'So'\n        WHEN '1' THEN 'Mo'\n        WHEN '2' THEN 'Di'\n        WHEN '3' THEN 'Mi'\n        WHEN '4' THEN 'Do'\n        WHEN '5' THEN 'Fr'\n        WHEN '6' THEN 'Sa'\n    END AS Wochentag,\n\n    -- Tages-COP\n    sum(Wärmeleistung) / 1000\n    / (sum(elektrische_Leistung * 1.07) / 1000) AS Tages_AZ\nFROM temperature_snapshots_stat T1\n\n-- optional: auch die Anzeige erst ab Startdatum\nWHERE strftime('%F', timestamp_mez) <= strftime('%F', datetime(1769930839587 / 1000, 'unixepoch', 'localtime'))\nand installation_id = 1234567 \n\nGROUP BY strftime('%F', timestamp_mez)\nORDER BY strftime('%F', timestamp_mez) desc\nLimit 14\n",
     "rawQueryText": "SELECT\n      strftime('%d.%m', timestamp_mez) as 'Datum',\n      CASE strftime('%w', timestamp_mez)\n        WHEN '0' THEN 'So'\n        WHEN '1' THEN 'Mo'\n        WHEN '2' THEN 'Di'\n        WHEN '3' THEN 'Mi'\n        WHEN '4' THEN 'Do'\n        WHEN '5' THEN 'Fr'\n        WHEN '6' THEN 'Sa'\n    END AS Wochentag,\n\n    -- Tages-COP\n    sum(Wärmeleistung) / 1000\n    / (sum(elektrische_Leistung * ${korrekturfaktor}) / 1000) AS Tages_AZ\nFROM temperature_snapshots_stat T1\n\n-- optional: auch die Anzeige erst ab Startdatum\nWHERE strftime('%F', timestamp_mez) <= strftime('%F', datetime($__to / 1000, 'unixepoch', 'localtime'))\nand installation_id = ${anlage_id} \n\nGROUP BY strftime('%F', timestamp_mez)\nORDER BY strftime('%F', timestamp_mez) desc\nLimit 14\n",
     "rawSql": "SELECT (MAX(thermal_energy)-MIN(thermal_energy))/(MAX(electrical_energy)-MIN(electrical_energy)) AS value FROM temperature_snapshots_grafana WHERE installation_id = '7654321', strftime('%Y-%m',timestamp)=strftime('Y-%m','now')",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "TAZ - Heute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n   sum(Wärmeleistung) / sum(elektrische_Leistung * 1.0)\n       \nFrom temperature_snapshots_stat\nwhere  installation_id = 1234567 \ngroup by strftime('%F', timestamp_mez)\norder by timestamp_mez desc\nLimit 1\n",
     "rawQueryText": "SELECT\n   sum(Wärmeleistung) / sum(elektrische_Leistung * ${korrekturfaktor})\n       \nFrom temperature_snapshots_stat\nwhere  installation_id = ${anlage_id} \ngroup by strftime('%F', timestamp_mez)\norder by timestamp_mez desc\nLimit 1\n",
     "rawSql": "SELECT (MAX(thermal_energy)-MIN(thermal_energy))/(MAX(electrical_energy)-MIN(electrical_energy)) AS value FROM temperature_snapshots_grafana WHERE installation_id = '7654321', date(timestamp)=date('now')",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "JAZ WJ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n \n         sum(Wärmeleistung / 1000) /\n         sum(elektrische_Leistung / 1000 * 1.0)\n          \nFROM temperature_snapshots_stat \nWHERE strftime('%F', timestamp_mez) >= \n  substr('16.12.2025', 7,4) || '-' || \n  substr('16.12.2025', 4,2) || '-' || \n  substr('16.12.2025', 1,2)\nand installation_id = 1234567 \n",
     "rawQueryText": "SELECT\n \n         sum(Wärmeleistung / 1000) /\n         sum(elektrische_Leistung / 1000 * ${korrekturfaktor})\n          \nFROM temperature_snapshots_stat \nWHERE strftime('%F', timestamp_mez) >= \n  substr('${start_wirtschaftsjahr}', 7,4) || '-' || \n  substr('${start_wirtschaftsjahr}', 4,2) || '-' || \n  substr('${start_wirtschaftsjahr}', 1,2)\nand installation_id = ${anlage_id} \n",
     "rawSql": "SELECT (MAX(thermal_energy)-MIN(thermal_energy))/(MAX(electrical_energy)-MIN(electrical_energy)) AS value FROM temperature_snapshots_grafana WHERE installation_id = '7654321', date(timestamp)=date('now')",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "MAZ lfd. Monat",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "\nSELECT \n        CASE\n        when 'Monat' = 'Monat'\n        then strftime('%Y-%m', timestamp_mez)\n        else strftime('%Y', timestamp_mez)\n        END AS periode,\n\n    sum(Wärmeleistung / 1000) / (sum(elektrische_Leistung / 1000 * 1.0)) AS 'Arbeitszahl'\n\n    FROM temperature_snapshots_stat\n\n    WHERE installation_id = 1234567\n    AND (\n    (\n     'Monat' = 'Monat'\n     AND strftime('%Y-%m', timestamp_mez) = \n     strftime('%Y-%m', datetime(1770714608029 / 1000, 'unixepoch', 'localtime'))\n    )\n    OR\n    (\n     'Monat' <> 'Monat'\n     AND strftime('%Y', timestamp_mez) =\n     strftime('%Y', datetime(1770714608029 / 1000, 'unixepoch', 'localtime'))\n    )\n    )\n    \nGROUP BY periode\nORDER BY periode DESC\nLimit 1",
     "rawQueryText": "\nSELECT \n        CASE\n        when ${granularity} = 'Monat'\n        then strftime('%Y-%m', timestamp_mez)\n        else strftime('%Y', timestamp_mez)\n        END AS periode,\n\n    sum(Wärmeleistung / 1000) / (sum(elektrische_Leistung / 1000 * ${korrekturfaktor})) AS 'Arbeitszahl'\n\n    FROM temperature_snapshots_stat\n\n    WHERE installation_id = ${anlage_id}\n    AND (\n    (\n     ${granularity} = 'Monat'\n     AND strftime('%Y-%m', timestamp_mez) = \n     strftime('%Y-%m', datetime($__to / 1000, 'unixepoch', 'localtime'))\n    )\n    OR\n    (\n     ${granularity} <> 'Monat'\n     AND strftime('%Y', timestamp_mez) =\n     strftime('%Y', datetime($__to / 1000, 'unixepoch', 'localtime'))\n    )\n    )\n    \nGROUP BY periode\nORDER BY periode DESC\nLimit 1",
     "rawSql": "SELECT MAX(compressor_hours)-MIN(compressor_hours) AS value FROM temperature_snapshots_grafana WHERE installation_id = '7654321', date(timestamp)=date('now')",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "KWh / Tag (lfd. Monat)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  CASE\n    WHEN ${granularity} = 'Monat'\n      THEN strftime('%Y-%m', timestamp_mez)\n    ELSE strftime('%Y', timestamp_mez)\n  END AS periode,\n\n  sum(elektrische_leistung / 1000 * ${korrekturfaktor})\n/\nCASE\n  WHEN ${granularity} = 'Monat' THEN\n    (\n      julianday(max(timestamp_mez))\n      - julianday(date(max(timestamp_mez)))\n      - 1\n      + cast(strftime('%d', max(timestamp_mez)) AS real)\n    )\n  ELSE\n    (\n      julianday(max(timestamp_mez))\n      - julianday(date(max(timestamp_mez), 'start of year'))\n    )\nEND\n\nFROM temperature_snapshots_stat\n\nWHERE installation_id = ${anlage_id}\n  AND (\n    (\n      ${granularity} = 'Monat'\n      AND strftime('%Y-%m', timestamp_mez) =\n               strftime('%Y-%m', datetime($__to / 1000, 'unixepoch', 'localtime'))\n    )\n    OR\n    (\n      ${granularity} <> 'Monat' \n      AND strftime('%Y', timestamp_mez) = \n               strftime('%Y', datetime($__to / 1000, 'unixepoch', 'localtime'))\n    )\n  )\n\nGROUP BY periode\nORDER BY periode DESC\nLIMIT 1",
     "rawQueryText": "SELECT\n  CASE\n    WHEN ${granularity} = 'Monat'\n      THEN strftime('%Y-%m', timestamp_mez)\n    ELSE strftime('%Y', timestamp_mez)\n  END AS periode,\n\n  sum(elektrische_leistung / 1000 * ${korrekturfaktor})\n/\nCASE\n  WHEN ${granularity} = 'Monat' THEN\n    (\n      julianday(max(timestamp_mez))\n      - julianday(date(max(timestamp_mez)))\n      - 1\n      + cast(strftime('%d', max(timestamp_mez)) AS real)\n    )\n  ELSE\n    (\n      julianday(max(timestamp_mez))\n      - julianday(date(max(timestamp_mez), 'start of year'))\n    )\nEND\n\nFROM temperature_snapshots_stat\n\nWHERE installation_id = ${anlage_id}\n  AND (\n    (\n      ${granularity} = 'Monat'\n      AND strftime('%Y-%m', timestamp_mez) =\n               strftime('%Y-%m', datetime($__to / 1000, 'unixepoch', 'localtime'))\n    )\n    OR\n    (\n      ${granularity} <> 'Monat' \n      AND strftime('%Y', timestamp_mez) = \n               strftime('%Y', datetime($__to / 1000, 'unixepoch', 'localtime'))\n    )\n  )\n\nGROUP BY periode\nORDER BY periode DESC\nLIMIT 1",
     "rawSql": "SELECT MAX(compressor_hours)-MIN(compressor_hours) AS value FROM temperature_snapshots_grafana WHERE installation_id = '7654321', date(timestamp)=date('now')",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Tage ohne Laufzeit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n    periode,\n    SUM(day_inactive) AS inactive_days\nFROM (\n    SELECT \n        CASE\n        when 'Monat' = 'Monat'\n        then strftime('%Y-%m', timestamp_mez)\n        else strftime('%Y', timestamp_mez)\n        END AS periode,\n\n    strftime('%Y-%m-%d', timestamp_mez) AS day,\n\n        CASE\n            WHEN SUM(compressor_active) > 0 THEN 0\n            ELSE 1\n        END AS day_inactive\n\n    FROM temperature_snapshots_stat\n\n    WHERE installation_id = 1234567\n    AND (\n    (\n     'Monat' = 'Monat'\n     AND strftime('%Y-%m', timestamp_mez) = \n     strftime('%Y-%m', datetime(1770714870182 / 1000, 'unixepoch', 'localtime'))\n    )\n    OR\n    (\n     'Monat' <> 'Monat'\n     AND strftime('%Y', timestamp_mez) =\n     strftime('%Y', datetime(1770714870182 / 1000, 'unixepoch', 'localtime'))\n    )\n    )\n    group by periode, day\n   ) \nGROUP BY periode\nORDER BY periode DESC\nLimit 1",
     "rawQueryText": "SELECT\n    periode,\n    SUM(day_inactive) AS inactive_days\nFROM (\n    SELECT \n        CASE\n        when ${granularity} = 'Monat'\n        then strftime('%Y-%m', timestamp_mez)\n        else strftime('%Y', timestamp_mez)\n        END AS periode,\n\n    strftime('%Y-%m-%d', timestamp_mez) AS day,\n\n        CASE\n            WHEN SUM(compressor_active) > 0 THEN 0\n            ELSE 1\n        END AS day_inactive\n\n    FROM temperature_snapshots_stat\n\n    WHERE installation_id = ${anlage_id}\n    AND (\n    (\n     ${granularity} = 'Monat'\n     AND strftime('%Y-%m', timestamp_mez) = \n     strftime('%Y-%m', datetime($__to / 1000, 'unixepoch', 'localtime'))\n    )\n    OR\n    (\n     ${granularity} <> 'Monat'\n     AND strftime('%Y', timestamp_mez) =\n     strftime('%Y', datetime($__to / 1000, 'unixepoch', 'localtime'))\n    )\n    )\n    group by periode, day\n   ) \nGROUP BY periode\nORDER BY periode DESC\nLimit 1",
     "rawSql": "SELECT MAX(compressor_hours)-MIN(compressor_hours) AS value FROM temperature_snapshots_grafana WHERE installation_id = '7654321', date(timestamp)=date('now')",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Leistungsaufnahme (lfd. Monat)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  CASE\n    WHEN ${granularity} = 'Monat'\n      THEN strftime('%Y-%m', timestamp_mez)\n    ELSE strftime('%Y', timestamp_mez)\n  END AS periode,\n\nsum(elektrische_leistung / 1000 * ${korrekturfaktor}) AS 'Monatsstromverbrauch'\n\nFROM temperature_snapshots_stat\n\nWHERE installation_id = ${anlage_id}\n  AND (\n    (\n      ${granularity} = 'Monat'\n      AND strftime('%Y-%m', timestamp_mez) =\n               strftime('%Y-%m', datetime($__to / 1000, 'unixepoch', 'localtime'))\n    )\n    OR\n    (\n      ${granularity} <> 'Monat' \n      AND strftime('%Y', timestamp_mez) = \n               strftime('%Y', datetime($__to / 1000, 'unixepoch', 'localtime'))\n    )\n  )\n\nGROUP BY periode\nORDER BY periode DESC\nLIMIT 1",
     "rawQueryText": "SELECT\n  CASE\n    WHEN ${granularity} = 'Monat'\n      THEN strftime('%Y-%m', timestamp_mez)\n    ELSE strftime('%Y', timestamp_mez)\n  END AS periode,\n\nsum(elektrische_leistung / 1000 * ${korrekturfaktor}) AS 'Monatsstromverbrauch'\n\nFROM temperature_snapshots_stat\n\nWHERE installation_id = ${anlage_id}\n  AND (\n    (\n      ${granularity} = 'Monat'\n      AND strftime('%Y-%m', timestamp_mez) =\n               strftime('%Y-%m', datetime($__to / 1000, 'unixepoch', 'localtime'))\n    )\n    OR\n    (\n      ${granularity} <> 'Monat' \n      AND strftime('%Y', timestamp_mez) = \n               strftime('%Y', datetime($__to / 1000, 'unixepoch', 'localtime'))\n    )\n  )\n\nGROUP BY periode\nORDER BY periode DESC\nLIMIT 1",
     "rawSql": "SELECT MAX(compressor_hours)-MIN(compressor_hours) AS value FROM temperature_snapshots_grafana WHERE installation_id = '7654321', date(timestamp)=date('now')",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Wärmeleistung (lfd. Monat)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  CASE\n    WHEN ${granularity} = 'Monat'\n      THEN strftime('%Y-%m', timestamp_mez)\n    ELSE strftime('%Y', timestamp_mez)\n  END AS periode,\n\nsum(Wärmeleistung / 1000) AS 'Monatswärmeleistung'\n\nFROM temperature_snapshots_stat\n\nWHERE installation_id = ${anlage_id}\n  AND (\n    (\n      ${granularity} = 'Monat'\n      AND strftime('%Y-%m', timestamp_mez) =\n               strftime('%Y-%m', datetime($__to / 1000, 'unixepoch', 'localtime'))\n    )\n    OR\n    (\n      ${granularity} <> 'Monat' \n      AND strftime('%Y', timestamp_mez) = \n               strftime('%Y', datetime($__to / 1000, 'unixepoch', 'localtime'))\n    )\n  )\n\nGROUP BY periode\n\nORDER BY periode DESC\nLIMIT 1",
     "rawQueryText": "SELECT\n  CASE\n    WHEN ${granularity} = 'Monat'\n      THEN strftime('%Y-%m', timestamp_mez)\n    ELSE strftime('%Y', timestamp_mez)\n  END AS periode,\n\nsum(Wärmeleistung / 1000) AS 'Monatswärmeleistung'\n\nFROM temperature_snapshots_stat\n\nWHERE installation_id = ${anlage_id}\n  AND (\n    (\n      ${granularity} = 'Monat'\n      AND strftime('%Y-%m', timestamp_mez) =\n               strftime('%Y-%m', datetime($__to / 1000, 'unixepoch', 'localtime'))\n    )\n    OR\n    (\n      ${granularity} <> 'Monat' \n      AND strftime('%Y', timestamp_mez) = \n               strftime('%Y', datetime($__to / 1000, 'unixepoch', 'localtime'))\n    )\n  )\n\nGROUP BY periode\n\nORDER BY periode DESC\nLIMIT 1",
     "rawSql": "SELECT MAX(compressor_hours)-MIN(compressor_hours) AS value FROM temperature_snapshots_grafana WHERE installation_id = '7654321', date(timestamp)=date('now')",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}